### ISSUE TITLE
Suggestion: Change Database in ItemWrapper

### ISSUE THREAD

**Issue by mikaelnet** [Fortis-Collection/fortis#17]
The Database property in ItemWrapper currently returns the Context.Database by default. This means that the Database property may not return the correct database for a wrapped item. This applies in background processes etc. 

I suggest the method should first test if _item != null then return _item.Database else return Factory.GetDatabase(this.DatabaseName). 

However, the internal Item property has a dependency on that property as well and I haven't investigated how this change would affect lazy loading.

If that doesn't work, I suggest making the Database property internal as well. The current implementation can cause a lot of trouble.

**Comment by jasonbert** [comment]
I don't think the Database property should even be there really as it's exposing the Sitecore API :). Definitely right though that in its current guise it should be returning the database associated with the item.

Maybe the best option is to change the property to return the Database name. I would then return null for lazy load or it can access the internal Item property which will retrieve the item.

Definitely something to look at.

**Comment by mikaelnet** [comment]
I agree. In a way, it's a bit odd to expose the database, but I very much like the way Fortis is wrapping the Sitecore internals, and that we're still able to get the wrapped items in order to perform more advanced operation. 

Regarding lazy load, I think it should load the item and return the database, as with any other lazy loaded field.

**Comment by mikaelnet** [comment]
I've had look into this now, and I've found that there's pretty much code in the ItemFactory depending on the Context.Database, so it seems like there would be a some breaking changes if I'd correct this everywhere. I've made a fork and I'll try to solve this. Maybe there'll be some time on the summit to discuss this?

**Comment by jasonbert** [comment]
All the usages of Context.Database in the ItemFactory class aren't connected to the IItemWrapper interface. It should be safe to make changes to the ItemWrapper implementation.

**Comment by GuitarRich** [comment]
Database properties have been removed from the interfaces. They were added by mistake in the first place.
