### ISSUE TITLE
Suggestion: Save() params

### ISSUE THREAD

**Issue by mikaelnet** [Fortis-Collection/fortis#19]
Since Fortis have support for the most common CRUD operations, it's really useful when doing integration as well. However, I just realized it would be very useful if IItemWrapper.Save() could expose the two underlying updateStatistics and silent optional parameters as well.

One could maybe argue that Recycle, Archive, Clone and potentially other operations as well could be added, but maybe that's taking it a bit too far. 

If you want, I can help you with coding these things as well.

**Comment by jasonbert** [comment]
Feel free to make pull requests at any time :).

**Comment by GuitarRich** [comment]
Added both overloads for the Save method on the item wrapper. Will be released in v4
