### ISSUE TITLE
Original should be marked with [JsonIgnore] attribute

### ISSUE THREAD

**Issue by GuitarRich** [Fortis-Collection/fortis#30]
Can't serialize an `IItemWrapper` or `IFieldWrapper` because the `.Original` property has a circular reference in it.

**Comment by johnduhart** [comment]
I'm not sure Fortis should take a Dependency on Json.Net for this. Can this be achieved by the end user by overriding the property?

**Comment by GuitarRich** [comment]
It can on the `IItemWrapper` easily enough. Its a little harder for the `IFieldWrapper` tho. Although the updates in v4 make it possible you would still have to override all field wrappers that you wanted to serialize.

**Comment by GuitarRich** [comment]
@jasonbert what's your opinion on this?

**Comment by jasonbert** [comment]
To me this doesn't seem like a good idea. Also what would you do when it came to deserialization? Don't you need to provide a concrete class for that?

**Comment by GuitarRich** [comment]
Wont fix
