### ISSUE TITLE
Release 4.2.1, Nuget package wrong targetFramework

### ISSUE THREAD

**Issue by GabrielCodehouse** [Fortis-Collection/fortis#35]
In your latest release, the Forti.dll is compiled against .NET 4.5.2 instead of 4.5 as expected in the net45 folder.
Please rectify if Fortis can support 4.5, if not remove the folder all together.

**Comment by GuitarRich** [comment]
the Nuget package has been updated to put the binary into the net452 folder. As MS support has dropped for 4.5 and 4.5.1 we will not be adding binaries compiled against those versions.
